# Spring Boot 설정
spring:
  profiles:
    active: dev
    # 'secret' 프로필을 포함하여 민감한 정보 관리
    include: secret
  # JPA (Java Persistence API) 설정
  jpa:
    # Hibernate 설정
    hibernate:
      # DDL (Data Definition Language) 자동 생성 전략을 'create'로 설정
      # 애플리케이션 시작 시 스키마를 새로 생성
      ddl-auto: create
    # Hibernate 추가 속성
    properties:
      hibernate:
        # 실행되는 SQL 쿼리를 로그에 표시
        show_sql: true
        # SQL 쿼리를 보기 좋게 포맷팅
        format_sql: true
        # SQL 쿼리에 주석 추가
        use_sql_comments: true
# 로깅 설정
logging:
  # 로깅 레벨 설정
  level:
    # 루트 로거의 레벨을 'INFO'로 설정
    root: INFO
    # 'com.example.sksb' 패키지의 레벨을 'DEBUG'로 설정
    com.example.sksb: DEBUG
    # Hibernate JDBC 바인딩 파라미터 로깅을 'TRACE'로 설정
    org.hibernate.prm.jdbc.bind: TRACE
    # Hibernate JDBC 결과 추출 로깅을 'TRACE'로 설정
    ort.hibernate.orm.jdbc.extract: TRACE
