spring:
  profile:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com:example.sksb: DEBUG
    org.hiernate.prm.jdbc.bind: TRACE
    ort.hibernate.orm.jdbc.extract: TRACE